name: hanzi_writer_data_flutter
description: A tiny Flutter utility to load Chinese character stroke order data offline.
version: 0.0.1
homepage: https://github.com/roystontay/hanzi-writer-data-flutter
repository: https://github.com/roystontay/hanzi-writer-data-flutter
issue_tracker: https://github.com/roystontay/hanzi-writer-data-flutter

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/hanzi/
  